language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

before_install:
  - ./oci8.sh
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
